const data = [
    {
        "web-scraper-order": "1712881413-1",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/gigabyte-aorus-15-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-tb-ssd-10256951.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10256951_001?$t-thumbnail$&fmt=auto",
        "name": "GIGABYTE AORUS 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 TB SSD"
    },
    {
        "web-scraper-order": "1712881413-2",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/gigabyte-aorus-15-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-tb-ssd-10256951.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10256951_002?$t-thumbnail$&fmt=auto",
        "name": "GIGABYTE AORUS 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 TB SSD"
    },
    {
        "web-scraper-order": "1712881413-3",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/gigabyte-aorus-15-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-tb-ssd-10256951.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10256951_003?$t-thumbnail$&fmt=auto",
        "name": "GIGABYTE AORUS 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 TB SSD"
    },
    {
        "web-scraper-order": "1712881413-4",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/gigabyte-aorus-15-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-tb-ssd-10256951.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10256951_004?$t-thumbnail$&fmt=auto",
        "name": "GIGABYTE AORUS 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 TB SSD"
    },
    {
        "web-scraper-order": "1712881413-5",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/gigabyte-aorus-15-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-tb-ssd-10256951.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10256951_005?$t-thumbnail$&fmt=auto",
        "name": "GIGABYTE AORUS 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 TB SSD"
    },
    {
        "web-scraper-order": "1712881415-6",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-katana-15-15.6-gaming-laptop-intel-core-i7-rtx-4050-1-tb-ssd-10246626.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246626_001?$t-thumbnail$&fmt=auto",
        "name": "MSI Katana 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881415-7",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-katana-15-15.6-gaming-laptop-intel-core-i7-rtx-4050-1-tb-ssd-10246626.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246626_002?$t-thumbnail$&fmt=auto",
        "name": "MSI Katana 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881415-8",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-katana-15-15.6-gaming-laptop-intel-core-i7-rtx-4050-1-tb-ssd-10246626.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246626_003?$t-thumbnail$&fmt=auto",
        "name": "MSI Katana 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881415-9",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-katana-15-15.6-gaming-laptop-intel-core-i7-rtx-4050-1-tb-ssd-10246626.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246626_004?$t-thumbnail$&fmt=auto",
        "name": "MSI Katana 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881415-10",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-katana-15-15.6-gaming-laptop-intel-core-i7-rtx-4050-1-tb-ssd-10246626.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246626_005?$t-thumbnail$&fmt=auto",
        "name": "MSI Katana 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881418-11",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-f15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10246637.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246637_001?$t-thumbnail$&fmt=auto",
        "name": "ASUS TUF Gaming F15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881418-12",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-f15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10246637.html",
        "imgs-src": "//flv.isitetv.com/media/video/3342/ol_video_img_url__275544_3342.jpg?m=3342&r=1048&t=1",
        "name": "ASUS TUF Gaming F15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881418-13",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-f15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10246637.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246637_002?$t-thumbnail$&fmt=auto",
        "name": "ASUS TUF Gaming F15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881418-14",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-f15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10246637.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246637_003?$t-thumbnail$&fmt=auto",
        "name": "ASUS TUF Gaming F15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881418-15",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-f15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10246637.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246637_004?$t-thumbnail$&fmt=auto",
        "name": "ASUS TUF Gaming F15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881421-16",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-2050-512-gb-ssd-10253504.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253504_001?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 2050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881421-17",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-2050-512-gb-ssd-10253504.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253504_002?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 2050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881421-18",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-2050-512-gb-ssd-10253504.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253504_003?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 2050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881421-19",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-2050-512-gb-ssd-10253504.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253504_004?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 2050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881421-20",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-2050-512-gb-ssd-10253504.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253504_005?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 2050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881424-21",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/gigabyte-g6-16-gaming-laptop-intel-core-i7-rtx-4060-1-tb-ssd-10257149.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10257149_001?$t-thumbnail$&fmt=auto",
        "name": "GIGABYTE G6 16\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881424-22",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/gigabyte-g6-16-gaming-laptop-intel-core-i7-rtx-4060-1-tb-ssd-10257149.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10257149_002?$t-thumbnail$&fmt=auto",
        "name": "GIGABYTE G6 16\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881426-23",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/gigabyte-g5-kf-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-gb-ssd-10258060.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10258060_001?$t-thumbnail$&fmt=auto",
        "name": "GIGABYTE G5 KF 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881426-24",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/gigabyte-g5-kf-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-gb-ssd-10258060.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10258060_002?$t-thumbnail$&fmt=auto",
        "name": "GIGABYTE G5 KF 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881429-25",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-3050-1-tb-ssd-10253211.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253211_001?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881429-26",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-3050-1-tb-ssd-10253211.html",
        "imgs-src": "//flv.isitetv.com/media/video/1051/ol_video_img_url__276486_1051.jpg?m=1051&r=1048&t=1",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881429-27",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-3050-1-tb-ssd-10253211.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253211_002?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881429-28",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-3050-1-tb-ssd-10253211.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253211_003?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881429-29",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-3050-1-tb-ssd-10253211.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253211_004?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881432-30",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-ideapad-gaming-3-15.6-gaming-laptop-amd-ryzen-5-rtx-4050-512-gb-ssd-10249561.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10249561_001?$t-thumbnail$&fmt=auto",
        "name": "LENOVO IdeaPad Gaming 3 15.6\" Gaming Laptop - AMD Ryzen 5, RTX 4050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881432-31",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-ideapad-gaming-3-15.6-gaming-laptop-amd-ryzen-5-rtx-4050-512-gb-ssd-10249561.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10249561_002?$t-thumbnail$&fmt=auto",
        "name": "LENOVO IdeaPad Gaming 3 15.6\" Gaming Laptop - AMD Ryzen 5, RTX 4050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881432-32",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-ideapad-gaming-3-15.6-gaming-laptop-amd-ryzen-5-rtx-4050-512-gb-ssd-10249561.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10249561_003?$t-thumbnail$&fmt=auto",
        "name": "LENOVO IdeaPad Gaming 3 15.6\" Gaming Laptop - AMD Ryzen 5, RTX 4050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881432-33",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-ideapad-gaming-3-15.6-gaming-laptop-amd-ryzen-5-rtx-4050-512-gb-ssd-10249561.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10249561_004?$t-thumbnail$&fmt=auto",
        "name": "LENOVO IdeaPad Gaming 3 15.6\" Gaming Laptop - AMD Ryzen 5, RTX 4050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881432-34",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-ideapad-gaming-3-15.6-gaming-laptop-amd-ryzen-5-rtx-4050-512-gb-ssd-10249561.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10249561_005?$t-thumbnail$&fmt=auto",
        "name": "LENOVO IdeaPad Gaming 3 15.6\" Gaming Laptop - AMD Ryzen 5, RTX 4050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881434-35",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/hp-victus-15fa1502na-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-gb-ssd-10250487.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10250487_001?$t-thumbnail$&fmt=auto",
        "name": "HP Victus 15-fa1502na 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881434-36",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/hp-victus-15fa1502na-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-gb-ssd-10250487.html",
        "imgs-src": "//flv.isitetv.com/media/video/1054/ol_video_img_url__277057_1054.jpg?m=1054&r=1048&t=1",
        "name": "HP Victus 15-fa1502na 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881434-37",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/hp-victus-15fa1502na-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-gb-ssd-10250487.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10250487_002?$t-thumbnail$&fmt=auto",
        "name": "HP Victus 15-fa1502na 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881434-38",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/hp-victus-15fa1502na-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-gb-ssd-10250487.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10250487_003?$t-thumbnail$&fmt=auto",
        "name": "HP Victus 15-fa1502na 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881434-39",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/hp-victus-15fa1502na-15.6-gaming-laptop-intel-core-i5-rtx-4060-512-gb-ssd-10250487.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10250487_004?$t-thumbnail$&fmt=auto",
        "name": "HP Victus 15-fa1502na 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881437-40",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-ideapad-gaming-3-16-gaming-laptop-amd-ryzen-5-rtx-3050-512-gb-ssd-10257413.html",
        "imgs-src": "",
        "name": "LENOVO IdeaPad Gaming 3 16\" Gaming Laptop - AMD Ryzen 5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881440-41",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-a15-15.6-gaming-laptop-amd-ryzen-7-rtx-3060-512-gb-ssd-10259874.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10259874_001?$t-thumbnail$&fmt=auto",
        "name": "ASUS TUF Gaming A15 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881440-42",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-a15-15.6-gaming-laptop-amd-ryzen-7-rtx-3060-512-gb-ssd-10259874.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10259874_002?$t-thumbnail$&fmt=auto",
        "name": "ASUS TUF Gaming A15 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881440-43",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-a15-15.6-gaming-laptop-amd-ryzen-7-rtx-3060-512-gb-ssd-10259874.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10259874_003?$t-thumbnail$&fmt=auto",
        "name": "ASUS TUF Gaming A15 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881440-44",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-a15-15.6-gaming-laptop-amd-ryzen-7-rtx-3060-512-gb-ssd-10259874.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10259874_004?$t-thumbnail$&fmt=auto",
        "name": "ASUS TUF Gaming A15 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881440-45",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/asus-tuf-gaming-a15-15.6-gaming-laptop-amd-ryzen-7-rtx-3060-512-gb-ssd-10259874.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10259874_005?$t-thumbnail$&fmt=auto",
        "name": "ASUS TUF Gaming A15 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881442-46",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-legion-slim-5-16-gaming-laptop-amd-ryzen-7-rtx-4060-1-tb-ssd-10253406.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253406_001?$t-thumbnail$&fmt=auto",
        "name": "LENOVO Legion Slim 5 16\" Gaming Laptop - AMD Ryzen 7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881442-47",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-legion-slim-5-16-gaming-laptop-amd-ryzen-7-rtx-4060-1-tb-ssd-10253406.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253406_002?$t-thumbnail$&fmt=auto",
        "name": "LENOVO Legion Slim 5 16\" Gaming Laptop - AMD Ryzen 7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881442-48",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-legion-slim-5-16-gaming-laptop-amd-ryzen-7-rtx-4060-1-tb-ssd-10253406.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253406_003?$t-thumbnail$&fmt=auto",
        "name": "LENOVO Legion Slim 5 16\" Gaming Laptop - AMD Ryzen 7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881442-49",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-legion-slim-5-16-gaming-laptop-amd-ryzen-7-rtx-4060-1-tb-ssd-10253406.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253406_004?$t-thumbnail$&fmt=auto",
        "name": "LENOVO Legion Slim 5 16\" Gaming Laptop - AMD Ryzen 7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881442-50",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/lenovo-legion-slim-5-16-gaming-laptop-amd-ryzen-7-rtx-4060-1-tb-ssd-10253406.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253406_005?$t-thumbnail$&fmt=auto",
        "name": "LENOVO Legion Slim 5 16\" Gaming Laptop - AMD Ryzen 7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881445-51",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10251897.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10251897_001?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881445-52",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10251897.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10251897_002?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881445-53",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10251897.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10251897_003?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881445-54",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10251897.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10251897_004?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881445-55",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i5-rtx-3050-512-gb-ssd-10251897.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10251897_005?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881448-56",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i7-rtx-4060-512-gb-ssd-10246640.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246640_001?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881448-57",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i7-rtx-4060-512-gb-ssd-10246640.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246640_002?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881448-58",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i7-rtx-4060-512-gb-ssd-10246640.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246640_003?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881448-59",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i7-rtx-4060-512-gb-ssd-10246640.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246640_004?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881448-60",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/msi-cyborg-15-15.6-gaming-laptop-intel-core-i7-rtx-4060-512-gb-ssd-10246640.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10246640_005?$t-thumbnail$&fmt=auto",
        "name": "MSI Cyborg 15 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 512 GB SSD"
    },
    {
        "web-scraper-order": "1712881451-61",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-16-16-gaming-laptop-amd-ryzen-7-rtx-4070-1.5-tb-ssd-10258171.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10258171_001?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 16 16\" Gaming Laptop - AMD Ryzen 7, RTX 4070, 1.5 TB SSD"
    },
    {
        "web-scraper-order": "1712881451-62",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-16-16-gaming-laptop-amd-ryzen-7-rtx-4070-1.5-tb-ssd-10258171.html",
        "imgs-src": "//flv.isitetv.com/media/video/1051/ol_video_img_url__282351_1051.jpg?m=1051&r=1048&t=1",
        "name": "ACER Nitro 16 16\" Gaming Laptop - AMD Ryzen 7, RTX 4070, 1.5 TB SSD"
    },
    {
        "web-scraper-order": "1712881451-63",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-16-16-gaming-laptop-amd-ryzen-7-rtx-4070-1.5-tb-ssd-10258171.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10258171_002?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 16 16\" Gaming Laptop - AMD Ryzen 7, RTX 4070, 1.5 TB SSD"
    },
    {
        "web-scraper-order": "1712881451-64",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-16-16-gaming-laptop-amd-ryzen-7-rtx-4070-1.5-tb-ssd-10258171.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10258171_003?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 16 16\" Gaming Laptop - AMD Ryzen 7, RTX 4070, 1.5 TB SSD"
    },
    {
        "web-scraper-order": "1712881451-65",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-16-16-gaming-laptop-amd-ryzen-7-rtx-4070-1.5-tb-ssd-10258171.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10258171_004?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 16 16\" Gaming Laptop - AMD Ryzen 7, RTX 4070, 1.5 TB SSD"
    },
    {
        "web-scraper-order": "1712881454-66",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-4060-1-tb-ssd-10253551.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253551_001?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881454-67",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-4060-1-tb-ssd-10253551.html",
        "imgs-src": "//flv.isitetv.com/media/video/1051/ol_video_img_url__276486_1051.jpg?m=1051&r=1048&t=1",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881454-68",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-4060-1-tb-ssd-10253551.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253551_002?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881454-69",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-4060-1-tb-ssd-10253551.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253551_003?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881454-70",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-15.6-gaming-laptop-intel-core-i7-rtx-4060-1-tb-ssd-10253551.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253551_004?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 15.6\" Gaming Laptop - Intel® Core™ i7, RTX 4060, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881457-71",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i7-rtx-4070-1-tb-ssd-10253173.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253173_001?$t-thumbnail$&fmt=auto",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i7, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881457-72",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i7-rtx-4070-1-tb-ssd-10253173.html",
        "imgs-src": "//flv.isitetv.com/media/video/1051/ol_video_img_url__276489_1051.jpg?m=1051&r=1048&t=1",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i7, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881457-73",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i7-rtx-4070-1-tb-ssd-10253173.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253173_002?$t-thumbnail$&fmt=auto",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i7, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881457-74",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i7-rtx-4070-1-tb-ssd-10253173.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253173_003?$t-thumbnail$&fmt=auto",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i7, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881457-75",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i7-rtx-4070-1-tb-ssd-10253173.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253173_004?$t-thumbnail$&fmt=auto",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i7, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881460-76",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i9-rtx-4070-1-tb-ssd-10253185.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253185_001?$t-thumbnail$&fmt=auto",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i9, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881460-77",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i9-rtx-4070-1-tb-ssd-10253185.html",
        "imgs-src": "//flv.isitetv.com/media/video/1051/ol_video_img_url__278835_1051.jpg?m=1051&r=1048&t=1",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i9, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881460-78",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i9-rtx-4070-1-tb-ssd-10253185.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253185_002?$t-thumbnail$&fmt=auto",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i9, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881460-79",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i9-rtx-4070-1-tb-ssd-10253185.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253185_003?$t-thumbnail$&fmt=auto",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i9, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881460-80",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-predator-helios-neo-16-gaming-laptop-intel-core-i9-rtx-4070-1-tb-ssd-10253185.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10253185_004?$t-thumbnail$&fmt=auto",
        "name": "ACER Predator Helios Neo 16\" Gaming Laptop - Intel® Core™ i9, RTX 4070, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881462-81",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an51546-15.6-gaming-laptop-amd-ryzen-7-rtx-3050-1-tb-ssd-10259222.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10259222_001?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 AN515-46 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881462-82",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an51546-15.6-gaming-laptop-amd-ryzen-7-rtx-3050-1-tb-ssd-10259222.html",
        "imgs-src": "//flv.isitetv.com/media/video/1051/ol_video_img_url__282351_1051.jpg?m=1051&r=1048&t=1",
        "name": "ACER Nitro 5 AN515-46 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881462-83",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an51546-15.6-gaming-laptop-amd-ryzen-7-rtx-3050-1-tb-ssd-10259222.html",
        "imgs-src": "/on/demandware.static/Sites-curryspcworlduk-Site/-/default/dw6d1b1d09/images/ajax-loader.gif",
        "name": "ACER Nitro 5 AN515-46 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881462-84",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an51546-15.6-gaming-laptop-amd-ryzen-7-rtx-3050-1-tb-ssd-10259222.html",
        "imgs-src": "/on/demandware.static/Sites-curryspcworlduk-Site/-/default/dw6d1b1d09/images/ajax-loader.gif",
        "name": "ACER Nitro 5 AN515-46 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881462-85",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an51546-15.6-gaming-laptop-amd-ryzen-7-rtx-3050-1-tb-ssd-10259222.html",
        "imgs-src": "/on/demandware.static/Sites-curryspcworlduk-Site/-/default/dw6d1b1d09/images/ajax-loader.gif",
        "name": "ACER Nitro 5 AN515-46 15.6\" Gaming Laptop - AMD Ryzen 7, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881465-86",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an5155853we-15.6-gaming-laptop-intel-core-i5-rtx-3050-1-tb-ssd-10254545.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10254545_001?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 AN515-58-53WE 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881465-87",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an5155853we-15.6-gaming-laptop-intel-core-i5-rtx-3050-1-tb-ssd-10254545.html",
        "imgs-src": "//flv.isitetv.com/media/video/1051/ol_video_img_url__278317_1051.jpg?m=1051&r=1048&t=1",
        "name": "ACER Nitro 5 AN515-58-53WE 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881465-88",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an5155853we-15.6-gaming-laptop-intel-core-i5-rtx-3050-1-tb-ssd-10254545.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10254545_002?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 AN515-58-53WE 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881465-89",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an5155853we-15.6-gaming-laptop-intel-core-i5-rtx-3050-1-tb-ssd-10254545.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10254545_003?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 AN515-58-53WE 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 1 TB SSD"
    },
    {
        "web-scraper-order": "1712881465-90",
        "web-scraper-start-url": "https://www.currys.co.uk/",
        "Gaming-link": "Gaming",
        "Gaming-link-href": "https://www.currys.co.uk/gaming",
        "sub-categorie-selector": "Gaming laptops",
        "sub-categorie-selector-href": "https://www.currys.co.uk/gaming/pc-gaming/gaming-laptops",
        "items": "View product",
        "items-href": "https://www.currys.co.uk/products/acer-nitro-5-an5155853we-15.6-gaming-laptop-intel-core-i5-rtx-3050-1-tb-ssd-10254545.html",
        "imgs-src": "https://media.currys.biz/i/currysprod/10254545_004?$t-thumbnail$&fmt=auto",
        "name": "ACER Nitro 5 AN515-58-53WE 15.6\" Gaming Laptop - Intel® Core™ i5, RTX 3050, 1 TB SSD"
    }
]


function groupData(data) {
    const result = [];
    const grouped = {};

    // Group data by the name of the laptop
    data.forEach(item => {
        if (!grouped[item.name]) {
            grouped[item.name] = {
                name: item.name,
                imgs_src: new Set() // Using a Set to avoid duplicates
            };
        }
        grouped[item.name].imgs_src.add(item["imgs-src"]);
    });

    // Convert grouped data into the desired format
    for (const key in grouped) {
        if (grouped.hasOwnProperty(key)) {
            const obj = {
                name: grouped[key].name,
                SecondaryImgs_src: Array.from(grouped[key].imgs_src).slice(1) // Convert Set to Array and skip the first image
            };
            result.push(obj);
        }
    }

    return result;
}

const groupedData = groupData(data);
console.log(groupedData);
